### ISSUE TITLE
unable to pass values into helm chart on install

### ISSUE THREAD

**Issue by dmitry-mightydevops** [fission/fission-charts#78]
```
➜ helm install --version v1.19.0 --namespace $FISSION_NAMESPACE fission fission-charts/fission-all --values fission-values.yaml 

Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: Namespace "fission" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "fission"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "fission"

```

fission-values.yaml:

```yaml
defaultNamespace: fission
builderNamespace: fission
functionNamespace: fission
additionalFissionNamespaces:
  - prod
```
